### ISSUE TITLE
some basic issues

### ISSUE THREAD

**Issue by smilethensee** [198808xc/OrganSegRSTN#4]
1、您好，请问初始化的时候只需要设置ENABLE_INITIALIZATION=1就可以了吗？因为源代码默认ENABLE_COARSE2FINE_TESTING=1。
2：在进行第二步我设置ENABLE_INDIV_TRAINING=1，其他都为0.然后报错
Traceback (most recent call last):
  File "indiv_training.py", line 98, in <module>
    if valid_loss(log_file, separate_iterations):
  File "/home/ubuntu/OrganSegRSTN/OrganSegRSTN/utils.py", line 63, in valid_loss
    text = open(log_file, 'r').read().splitlines()
IOError: [Errno 2] No such file or directory: '/home/ubuntu/DATA_PATH/logs/FD1:ZI3_1_20190627_222425.txt'
请问这个txt文件是怎么生成的呢?

**Comment by smilethensee** [comment]
在run.sh写路径名时少了一个/
